apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-component-name
    app.kubernetes.io/part-of: a
  name: a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: a
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:default-a
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
